# 访问
# http://localhost:8001/git-config/dev;http://localhost:8001/git-config/test;http://localhost:8001/git-config/prod
server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/JackFeng123/spring-cloud-examples.git
          # git仓库地址下的相对地址，可以配置多个，用,分割
          search-paths: config-repo
          username:
          password:
